<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//FR" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
    <head>
        <title>Gestionnaire de commandes d'artisanat</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="description" content="Gestionnaire de commandes de produits artisanaux" />
        <meta name="author" content="Alexis" />
        <link href="css/style.css" rel="stylesheet" type="text/css" />
        <link href="css/layout.css" rel="stylesheet" type="text/css" />

        <script type="text/javascript" src="js/jquery.js"></script>
    <!--    <script type="text/javascript" src="js/script.js"></script> -->

    </head>
    <body id="page">
        <div class="tail-top-right"></div>
        <div id="main">
            <!-- header -->
            <div id="header"></div>
            <!-- content -->
            <div id="content">
                <div class="wrapper">
                    <?php require $template; ?>
                </div>
            </div>
        </div>
    </body>
</html>
