<form action="<?php echo HTMLTools::buildURL('Register'); ?>" class="register" method="post">
    <div>
        <fieldset>
            <legend>User ID :</legend>
            <input type="text" name="userID" required="required" />
            <input type="submit" id="submit_button" value="Valider la commande" />
        </fieldset>
    </div>
    <br>
    <div>
        <fieldset>
            <legend>
                Catégorie des crafts demandés :
            </legend>

            Arme(s)
            <input type="hidden" value="0" id="hidden_weapons_check" name="weapons_checkbox" />
            <input type="checkbox" value="1" id="weapons_check" name="weapons_checkbox" />
            Armure(s)
            <input type="hidden" value="0" id="hidden_armors_check" name="armors_checkbox" />
            <input type="checkbox" value="1" id="armors_check" name="armors_checkbox" />

            <div>
                Glyphe(s)
                <input type="hidden" value="0" id="hidden_enchanting_check" name="enchanting_checkbox" />
                <input type="checkbox" value="1" id="enchanting_check" name="enchanting_checkbox" />
            </div>
            <div>
                Préparations alchimiques
                <input type="hidden" value="0" id="hidden_alchemy_check" name="alchemy_checkbox" />
                <input type="checkbox" value="1" id="alchemy_check" name="alchemy_checkbox" />
            </div>
        </fieldset>
    </div>
    <br>
    <div>
        <fieldset id="weaponsField" style="display:none">
            <table id="weaponsDataTable" class="form" border="1">
                <tbody>
                    <tr>
                        <td>
                            Arme :
                            <select name="weapon_kind[]">
                                <optgroup label="Forge">
                                    <?php foreach ($xml_equipment->weapons->blacksmithing->children() as $weapon): ?>
                                        <option><?php echo $weapon->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Travail du Bois">
                                    <?php foreach ($xml_equipment->weapons->woodworking->children() as $weapon): ?>
                                        <option><?php echo $weapon->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            </select>
                        </td>
                        <td>
                            Trait :
                            <select name="weapon_trait[]">
                                <option>Aucun trait</option>
                                <?php foreach ($xml_equipment->traits->weaponsTraits->children() as $trait): ?>
                                    <option><?php echo $trait->name; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td>
                            Niveau :
                            <select name="weapon_level[]">
                                <optgroup label="Niveau 1 - 50">
                                    <?php foreach ($xml_equipment->levels->lowLevels->children() as $level): ?>
                                        <option><?php echo $level->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Niveaux de Champion">
                                    <?php foreach ($xml_equipment->levels->highLevels->children() as $level): ?>
                                        <option><?php echo $level->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            </select>
                        </td>
                        <td>
                            Style :
                            <select name="weapon_style[]">
                                <optgroup label="Styles de base">
                                    <?php foreach ($xml_styles->baseGameStyles->commonStyles->children() as $style): ?>
                                        <option><?php echo $style->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Styles rares">
                                    <?php foreach ($xml_styles->baseGameStyles->rareStyles->children() as $style): ?>
                                        <option><?php echo $style->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Styles complexes">
                                    <?php foreach ($xml_styles->baseGameStyles->complexStyles->children() as $style): ?>
                                        <option><?php echo $style->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Styles de Cyrodiil">
                                    <?php foreach ($xml_styles->cyrodiilStyles->children() as $style): ?>
                                        <option><?php echo $style->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Styles d'Orsinium">
                                    <?php foreach ($xml_styles->orsiniumStyles->children() as $style): ?>
                                        <option><?php echo $style->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Styles du Trépas des Cognées">
                                    <?php foreach ($xml_styles->hewsBaneStyles->children() as $style): ?>
                                        <option><?php echo $style->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Styles de la Côte d'or">
                                    <?php foreach ($xml_styles->goldCoastStyles->children() as $style): ?>
                                        <option><?php echo $style->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Styles de la Gueule de Lorkhaj">
                                    <?php foreach ($xml_styles->mawOfLorkhajStyles->children() as $style): ?>
                                        <option><?php echo $style->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            </select>
                        </td>
                        <td>
                            Qualité :
                            <select name="weapon_quality[]">
                                <?php foreach ($xml_equipment->rarity->children() as $rarity): ?>
                                    <option><?php echo $rarity->name; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div>
                <input type="button" value="Ajouter une arme" id="weapons_add_button" />
                <input type="button" value="Supprimer une arme" id="weapons_remove_button" />
            </div>
        </fieldset>
    </div>
    <br>
    <div>
        <fieldset id="armorsField" style="display:none">
            <table id="armorsDataTable" class="form" border="1">
                <tbody>
                    <tr>
                        <td>
                            Armure :
                            <select name="armor_kind[]">
                                <optgroup label='Couture (léger)'>
                                    <?php foreach ($xml_equipment->armors->tailoring->light->children() as $armor): ?>
                                        <option><?php echo $armor->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label='Couture (moyen)'>
                                    <?php foreach ($xml_equipment->armors->tailoring->medium->children() as $armor): ?>
                                        <option><?php echo $armor->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label='Forge (lourd)'>
                                    <?php foreach ($xml_equipment->armors->blacksmithing->heavy->children() as $armor): ?>
                                        <option><?php echo $armor->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label='Travail du Bois'>
                                    <?php foreach ($xml_equipment->armors->woodworking->children() as $armor): ?>
                                        <option><?php echo $armor->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            </select>
                        </td>
                        <td>
                            Trait :
                            <select name="armor_trait[]">
                                <option>Aucun trait</option>
                                <?php foreach ($xml_equipment->traits->armorsTraits->children() as $trait): ?>
                                    <option><?php echo $trait->name; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td>
                            Niveau :
                            <select name="armor_level[]">
                                <optgroup label="Niveau 1 - 50">
                                    <?php foreach ($xml_equipment->levels->lowLevels->children() as $level): ?>
                                        <option><?php echo $level->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Niveaux de Champion">
                                    <?php foreach ($xml_equipment->levels->highLevels->children() as $level): ?>
                                        <option><?php echo $level->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            </select>
                        </td>
                        <td>
                            Style :
                            <select name="armor_style[]">
                                <optgroup label="Styles de base">
                                    <?php foreach ($xml_styles->baseGameStyles->commonStyles->children() as $style): ?>
                                        <option><?php echo $style->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Styles rares">
                                    <?php foreach ($xml_styles->baseGameStyles->rareStyles->children() as $style): ?>
                                        <option><?php echo $style->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Styles complexes">
                                    <?php foreach ($xml_styles->baseGameStyles->complexStyles->children() as $style): ?>
                                        <option><?php echo $style->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Styles de Cyrodiil">
                                    <?php foreach ($xml_styles->cyrodiilStyles->children() as $style): ?>
                                        <option><?php echo $style->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Styles d'Orsinium">
                                    <?php foreach ($xml_styles->orsiniumStyles->children() as $style): ?>
                                        <option><?php echo $style->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Styles du Trépas des Cognées">
                                    <?php foreach ($xml_styles->hewsBaneStyles->children() as $style): ?>
                                        <option><?php echo $style->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Styles de la Côte d'or">
                                    <?php foreach ($xml_styles->goldCoastStyles->children() as $style): ?>
                                        <option><?php echo $style->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Styles de la Gueule de Lorkhaj">
                                    <?php foreach ($xml_styles->mawOfLorkhajStyles->children() as $style): ?>
                                        <option><?php echo $style->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            </select>
                        </td>
                        <td>
                            Qualité :
                            <select name="armor_quality[]">
                                <?php foreach ($xml_equipment->rarity->children() as $rarity): ?>
                                    <option><?php echo $rarity->name; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div>
                <input type="button" value="Ajouter une armure" id="armors_add_button" />
                <input type="button" value="Supprimer une armure" id="armors_remove_button" />
            </div>
        </fieldset>
    </div>
    <br>
    <div>
        <fieldset id="enchantingField" style="display:none">
            <table id="enchantingDataTable" class="form" border="1">
                <tbody>
                    <tr>
                        <td>
                            Nom du glyphe :
                            <select name="glyph_kind[]">
                                <optgroup label="Glyphe d'armure">
                                    <?php foreach ($xml_enchanting->glyphs->armorGlyphs->children() as $glyph): ?>
                                        <option><?php echo $glyph->label; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Glyphe d'arme">
                                    <?php foreach ($xml_enchanting->glyphs->weaponGlyphs->children() as $glyph): ?>
                                        <option><?php echo $glyph->label; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Glyphe de bijou">
                                    <?php foreach ($xml_enchanting->glyphs->jewelryGlyphs->children() as $glyph): ?>
                                        <option><?php echo $glyph->label; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            </select>
                        </td>
                        <td>
                            Niveau :
                            <select name="glyph_level[]">
                                <optgroup label="Niveau 1 - 50">
                                    <?php foreach ($xml_enchanting->levels->lowLevels->children() as $level): ?>
                                        <option><?php echo $level->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Niveaux de Champion">
                                    <?php foreach ($xml_enchanting->levels->highLevels->children() as $level): ?>
                                        <option><?php echo $level->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            </select>
                        </td>
                        <td>
                            Qualité :
                            <select name="glyph_quality[]">
                                <?php foreach ($xml_enchanting->aspectRunes->children() as $rune): ?>
                                    <option><?php echo $rune->name; ?> (<?php echo $rune->traduction; ?>)</option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div>
                <input type="button" value="Ajouter un glyphe" id="enchanting_add_button" />
                <input type="button" value="Supprimer un glyphe" id="enchanting_remove_button" />
            </div>
        </fieldset>
    </div>
    <br>
    <div>
        <fieldset id="alchemyField" style="display:none">
            <table id="alchemyDataTable" class="form" border="1">
                <tbody>
                    <tr>
                        <td>
                            Solvant/Huile :
                            <select name="solvent[]">
                                <optgroup label="Solvants (Niveau 1 - 50)">
                                    <?php foreach ($xml_alchemy->solvents->lowLevel->children() as $solvent): ?>
                                        <option><?php echo $solvent->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Solvants (Niveaux de Champion)">
                                    <?php foreach ($xml_alchemy->solvents->highLevel->children() as $solvent): ?>
                                        <option><?php echo $solvent->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Huiles (Niveau 1 - 50)">
                                    <?php foreach ($xml_alchemy->oils->lowLevel->children() as $oil): ?>
                                        <option><?php echo $oil->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Huiles (Niveaux de Champion)">
                                    <?php foreach ($xml_alchemy->oils->highLevel->children() as $oil): ?>
                                        <option><?php echo $oil->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            </select>
                        </td>
                        <td>
                            Réactif 1 :
                            <select name="firstReagent[]">
                                <optgroup label="Botaniste">
                                    <?php foreach ($xml_alchemy->reagents->botanist->children() as $reagent): ?>
                                        <option><?php echo $reagent->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Toxicologue">
                                    <?php foreach ($xml_alchemy->reagents->toxicologist->children() as $reagent): ?>
                                        <option><?php echo $reagent->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            </select>
                        </td>
                        <td>
                            Réactif 2 :
                            <select name="secondReagent[]">
                                <optgroup label="Botaniste">
                                    <?php foreach ($xml_alchemy->reagents->botanist->children() as $reagent): ?>
                                        <option><?php echo $reagent->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Toxicologue">
                                    <?php foreach ($xml_alchemy->reagents->toxicologist->children() as $reagent): ?>
                                        <option><?php echo $reagent->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            </select>
                        </td>
                        <td>
                            Réactif 3 :
                            <select name="thirdReagent[]">
                                <optgroup label="Botaniste">
                                    <?php foreach ($xml_alchemy->reagents->botanist->children() as $reagent): ?>
                                        <option><?php echo $reagent->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                                <optgroup label="Toxicologue">
                                    <?php foreach ($xml_alchemy->reagents->toxicologist->children() as $reagent): ?>
                                        <option><?php echo $reagent->name; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            </select>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div>
                <input type="button" value="Ajouter une préparation" id="alchemy_add_button" />
                <input type="button" value="Supprimer une préparation" id="alchemy_remove_button" />
            </div>
        </fieldset>
    </div>
</form>
<script>
    enable_submit();
    enable_checkboxes();
    enable_weapons_table();
    enable_armors_table();
    enable_enchanting_table();
    enable_alchemy_table();
</script>
