<form action="<?php echo Plugin::createLink('send_form'); ?>" class="register" method="post">
    <?php $xml_equipment = simplexml_load_file('xml/equipment.xml') or die('Error: Cannot create object'); ?>
    <?php $xml_styles = simplexml_load_file('xml/styles.xml') or die('Error: Cannot create object'); ?>
    <div>
        <fieldset>
            <legend>User ID :</legend>
            <input type="text" name="user_field" />
        </fieldset>
    </div>
    <fieldset>
        <div>
            Arme(s)
            <input type="checkbox" id="weapons_check" name="weapons_check" />
            Armure(s)
            <input type="checkbox" id="armors_check" name="armors_check" />
        </div>
        <div>
            Glyphe(s)
            <input type="checkbox" id="enchanting_check" name="enchanting_check" />
        </div>
        <div>
            Préparations alchimiques
            <input type="checkbox" id="alchemy_check" name="alchemy_check" />
        </div>
    </fieldset>
    <fieldset>
        <table id="weaponsDataTable" class="form" border="1">
            <tbody>
                <tr>
                    <td>
                        Arme :
                        <select name="weapon_kind[]">
                            <optgroup label="Forge">
                                <?php foreach ($xml_equipment->weapons->blacksmithing->children() as $weapon): ?>
                                    <option><?php echo $weapon->name; ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                            <optgroup label="Travail du Bois">
                                <?php foreach ($xml_equipment->weapons->woodworking->children() as $weapon): ?>
                                    <option><?php echo $weapon->name; ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                        </select>
                    </td>
                    <td>
                        Trait :
                        <select name="weapon_trait[]">
                            <option>Aucun trait</option>
                            <?php foreach ($xml_equipment->traits->weaponsTraits->children() as $trait): ?>
                                <option><?php echo $trait->name; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <td>
                        Niveau de l'arme :
                        <select name="weapon_level[]">
                            <optgroup label="Niveau 1 - 50">
                                <?php foreach ($xml_equipment->levels->lowLevels->children() as $level): ?>
                                    <option><?php echo $level->name; ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                            <optgroup label="Niveaux de Champion">
                                <?php foreach ($xml_equipment->levels->highLevels->children() as $level): ?>
                                    <option><?php echo $level->name; ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                        </select>
                    </td>
                    <td>
                        Style de l'arme :
                        <select name="weapon_style[]">
                            <optgroup label="Styles de base">
                                <?php foreach ($xml_styles->baseGameStyles->commonStyles->children() as $style): ?>
                                    <option><?php echo $style->name; ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                            <optgroup label="Styles rares">
                                <?php foreach ($xml_styles->baseGameStyles->rareStyles->children() as $style): ?>
                                    <option><?php echo $style->name; ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                            <optgroup label="Styles complexes">
                                <?php foreach ($xml_styles->baseGameStyles->complexStyles->children() as $style): ?>
                                    <option><?php echo $style->name; ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                            <optgroup label="Styles de Cyrodiil">
                                <?php foreach ($xml_styles->cyrodiilStyles->children() as $style): ?>
                                    <option><?php echo $style->name; ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                            <optgroup label="Styles d'Orsinium">
                                <?php foreach ($xml_styles->orsiniumStyles->children() as $style): ?>
                                    <option><?php echo $style->name; ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                            <optgroup label="Styles du Trépas des Cognées">
                                <?php foreach ($xml_styles->hewsBaneStyles->children() as $style): ?>
                                    <option><?php echo $style->name; ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                            <optgroup label="Styles de la Côte d'or">
                                <?php foreach ($xml_styles->goldCoastStyles->children() as $style): ?>
                                    <option><?php echo $style->name; ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                            <optgroup label="Styles de la Gueule de Lorkhaj">
                                <?php foreach ($xml_styles->mawOfLorkhajStyles->children() as $style): ?>
                                    <option><?php echo $style->name; ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                        </select>
                    </td>
                    <td>
                        Qualité de l'arme :
                        <select name="weapon_quality[]">
                            <?php foreach ($xml_equipment->rarity->children() as $rarity): ?>
                                <option><?php echo $rarity->name; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
            </tbody>
        </table>
        <div>
            <input type="button" value="Ajouter une arme" id="weapons_add_button" />
            <input type="button" value="Supprimer une arme" id="weapons_remove_button" />
        </div>
    </fieldset>
</form>
<script>
init_weapons_table();
init_armors_table();
init_enchanting_table();
init_alchemy_table();
</script>
